### PR TITLE
Fix Invalid Resx file.

### PR DESCRIPTION
**Pull request by oleksis**

### CODE REVIEW

**Comment by Belim** [comment]
whoops, i see it now. I wrote last build without ☕ and np++ on the fly.  🤝

**Comment by oleksis** [comment]
Wy no add the content of the **data directory** to the source control (git) repository ?

**Comment by Belim** [comment]
I dont like having the data feed in the source repo so i will separate it from the code. There are also considerations  to offer a package in the MS Store. 
In this case, we would have to reload the data from a central location anyway

**Comment by Belim** [comment]
maybe we could document that in the readme so that you don't end up wondering where the data went 🤔

**Comment by oleksis** [comment]
I see good example for user compile de project from GitHub don’t have the data directory generated. And how we managed the changes for example `packages11.xml`  in the future ?

**Comment by Belim** [comment]
msix packages are storing the application data here` LocalAppDataDir\Packages\XXXBuiltbybel.TIW11_"emPACKAGEID"\Settings`

If we push the app into the store, you could simply check whether the data is available there during first start etc.., otherwise reload it from [collections](https://github.com/builtbybel/ThisIsWin11/tree/main/collections).

**Pull request merged**
